const data = {
  products: [
    {
      name: 'Arduino UNO',
      slug: 'Arduino UNO',
      category: 'Microcontrollers',
      image: '/images/3.png', // 679px × 829px
      price: 100,
      countInStock: 10,
      description:
        'Arduino Uno R3 Italy Genuine This is the Arduino Uno R3 Italy. As the title suggest this is the Genuine/ Original Board made from Italy, and not a clone which are usually made in China, though it is more expensive compared to the clones, the board is more robust and will last longer compared to a clone. In addition to all the features of the previous board, the Uno now uses an ATmega16U2. This allows for faster transfer rates and more memory. No drivers needed for Linux or Mac (inf file for Windows is needed and included in the Arduino IDE), and the ability to have the Uno show up as a keyboard, mouse, joystick, etc. The Uno R3 also adds SDA and SCL pins next to the AREF. In addition, there are two new pins placed near the RESET pin. One is the IOREF that allow the shields to adapt to the voltage provided from the board. The other is a not connected and is reserved for future purposes. The Uno R3 works with all existing shields but can adapt to new shields which use these additional pins. Features: ATmega328 microcontroller Input voltage - 7-12V 14 Digital I/O Pins (6 PWM outputs) 6 Analog Inputs 32k Flash Memory 16Mhz Clock Speed Documents: Schematic Eagle Files Product Page Arduino IDE Download.',
    },
    {
      name: 'Raspberry Pi',
      slug: 'Raspberry Pi',
      category: 'Microcontrollers',
      image: '/images/3.png',
      price: 10,
      countInStock: 20,
      // brand: 'Adidas',
      // rating: 4.0,
      // numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Servo Motor',
      slug: 'Servo Motor',
      category: 'Input/Output',
      image: '/images/3.png',
      price: 25,
      countInStock: 15,
      // brand: 'Nike',
      // rating: 4.5,
      // numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'LCD Screen',
      slug: 'LCD Screen',
      category: 'Input/Output',
      image: '/images/3.png',
      price: 65,
      countInStock: 5,
      // brand: 'Puma',
      // rating: 4.5,
      // numReviews: 10,
      description:
        'This 20×4 LCD display with I2C adapter board is based on the common HD44780 parallel interface chipset. The LCD display includes an I2C adapter board based on PCF8574 I2C chip, it converts I2C serial data to parallels data for the LCD display, thus, significantly reducing the number of I/O pins used on the micro-controller to send data to the LCD.',
    },
    {
      name: 'Ultrasonic Sensor',
      slug: 'Ultrasonic Sensorn',
      category: 'Sensor',
      image: '/images/3.png',
      price: 65,
      countInStock: 5,
      // brand: 'Puma',
      // rating: 4.5,
      // numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'PIR Sensor',
      slug: 'PIR Sensor',
      category: 'Sensor',
      image: '/images/3.png',
      price: 65,
      countInStock: 5,
      // brand: 'Puma',
      // rating: 4.5,
      // numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'IR Sensor',
      slug: 'IR Sensor',
      category: 'Sensor',
      image: '/images/3.png',
      price: 65,
      countInStock: 5,
      // brand: 'Puma',
      // rating: 4.5,
      // numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Membrane Keypad',
      slug: 'Membrane Keypad',
      category: 'Input/Output',
      image: '/images/3.png',
      price: 65,
      countInStock: 5,
      // brand: 'Puma',
      // rating: 4.5,
      // numReviews: 10,
      description: 'high quality product',
    },
    {
      name: '7 Segment Display',
      slug: '7 Segment Display',
      category: 'Input/Output',
      image: '/images/3.png',
      price: 65,
      countInStock: 5,
      // brand: 'Puma',
      // rating: 4.5,
      // numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'RFID Module',
      slug: 'Sensor',
      category: 'Input/Output',
      image: '/images/3.png',
      price: 65,
      countInStock: 5,
      // brand: 'Puma',
      // rating: 4.5,
      // numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
